### PR TITLE
feat(gui): select latest version on startup + game selection

### PR DESCRIPTION
**Pull request by lecoqjacob**
- setup code style + husky for commit hooks
- 
spicy-launcher_WLLPLJ9v7z

### CODE REVIEW

**Comment by orhun** [comment]
Cool, is this ready for review?

**Comment by lecoqjacob** [comment]
> Cool, is this ready for review?

it is ready freddy!

**Comment by orhun** [comment]
There seems to be a lot of changes and commits are not really scoped (`feat` includes formatting etc.). I'm not sure about the `husky` usage as well. Seems a bit hacky + there is a lot of `shellcheck` warnings. I wonder if we can simplify this to _only_ solve #2 and do nothing else. We can have separate PRs for other things.

**Comment by lecoqjacob** [comment]
I can definitely split up the workload into different prs.

Husky isn't a Jacky solution, it's widely known in the web dev world for running git hooks. I like to setup pre commit and pre push hooks to make sure the code is linted, styled and builds correctly. 

It's only Jacky because I setup some custom bash commands which look odd.

**Comment by zicklag** [comment]
I think splitting commits would be good. It's a little hard to find the latest version selection change in all the formatting changes.

About Husky, I'd be open to it conceptually, but I'm a little confused. What's husky doing exactly?

Doesn't git have a way to run bash scripts on commit? How is it different than just using normal [git hooks](https://git-scm.com/docs/githooks).?

**Comment by orhun** [comment]
> I think splitting commits would be good. It's a little hard to find the latest version selection change in all the formatting changes.

Yup, I agree.

**Review by orhun — APPROVED** [review]

**Pull request merged**
